name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Nx cloud ci run 
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js"

      - name: Install dependencies
        run: npm ci

      - name: Run all tests
        run: npx nx run-many --target=test --all --parallel
  
      - name: Nx Cloud - Complete CI Run
        run: npx nx-cloud complete-ci-run 
