name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Nx Cloud - Start CI Run
        run: npx nx-cloud start-ci-run
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          NX_BRANCH: ${{ github.ref }}
          NX_RUN_GROUP: ${{ github.run_id }}

      - name: Run all tests
        run: npx nx run-many --target=test --all --parallel
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: Nx Cloud - Stop CI Run
        run: npx nx-cloud stop-ci-run
